=== Devitzer/SMPTProject/public/Lines/LineSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["lineNumber", "lineName", "from", "to", "stops"],
    "properties": {
      "frequent": {
        "type": "boolean"
      },
      "lineNumber": {
        "type": "integer"
      },
      "lineName": {
        "type": "string"
      },
      "from": {
        "type": "string"
      },
      "to": {
        "type": "string"
      },
      "express": {
        "type": "boolean"
      },
      "ooi-express": {
        "type": "boolean"
      },
      "stops": {
        "type": "object",
        "minProperties": 1,
        "additionalProperties": {
          "type": "string"
        }
      }
    }
  }

=== Devitzer/SMPTProject/public/Lines/57.json
{
    "$schema": "./LineSchema.json",
    "frequent": true,
    "lineNumber": 57,
    "lineName": "Cote-Vertu",
    "from": "Pierre Elliott Trudeau Intl Airport",
    "to": "Station Saint-Michel",
    "stops": {
        "1": "Pierre Elliott Trudeau Intl Airport",
        "2": "Cote-Vertu / Pitfield",
        "3": "Cote-Vertu / Saint-Amour",
        "4": "Cote-Vertu / Montee de Liesse",
        "5": "Cote-Vertu / Begin",
        "6": "Cote-Vertu / No 3695",
        "7": "Cote-Vertu / Beaulac",
        "8": "Cote-Vertu / No 3200",
        "9": "Cote-Vertu / Cavendish",
        "10": "Cote-Vertu / Hocquart",
        "11": "Cote-Vertu / Bertrand",
        "12": "Cote-Vertu / Alexis-Nihon",
        "13": "Cote-Vertu / Saint-Aubin",
        "14": "Cote-Vertu / Marcel-Laurin",
        "15": "Cote-Vertu / Leduc",
        "16": "Cote-Vertu / Crevier",
        "17": "Station Cote-Vertu",
        "18": "Cote-Vertu / Saint-Germain",
        "19": "Cote-Vertu / Sainte-Croix",
        "20": "Cote-Vertu / Dutrisac",
        "21": "Cote-Vertu / Barre",
        "22": "Cote-Vertu / Montpellier",
        "23": "Cote-Vertu / Latour",
        "24": "Cote-Vertu / Muir",
        "25": "Cote-Vertu / Jules-Poitras",
        "26": "Cote-Vertu / Lebeau",
        "27": "Sauve / Elzear-Soucy",
        "28": "Sauve / de l'Acadie",
        "29": "Gare Ahuntsic",
        "30": "de l'Acadie / Louvain",
        "31": "de l'Acadie / Mazurette",
        "32": "de l'Acadie / Chabanel",
        "33": "de l'Acadie / Antonio-Barbeau",
        "34": "de l'Acadie / Legendre",
        "35": "de l'Acadie / Beauharnois",
        "36": "Cremazie / d'Outremont",
        "37": "Cremazie / Bloomfield",
        "38": "Cremazie / Querbes",
        "39": "Cremazie / Jeanne-Mance",
        "40": "Cremazie / de l'Esplanade",
        "41": "Cremazie / de Reims",
        "42": "Cremazie / Saint-Laurent",
        "43": "Cremazie / de Gaspe",
        "44": "Station Cremazie",
        "45": "Cremazie / Foucher",
        "46": "Cremazie / Saint-Hubert",
        "47": "Cremazie / Christophe-Colomb",
        "48": "Cremazie / Chambord",
        "49": "Cremazie / Rousselot",
        "50": "Cremazie / Fabre",
        "51": "Cremazie / Papineau",
        "52": "Cremazie / Chabot",
        "53": "Cremazie / de Lorimier",
        "54": "Cremazie / des Ecores",
        "55": "Cremazie / d'Iberville",
        "56": "Cremazie / 1e Avenue",
        "57": "Cremazie / 6e Avenue",
        "58": "Cremazie / 9e Avenue",
        "59": "Cremazie / Saint-Michel",
        "60": "Station Saint-Michel"
    }
}

=== Devitzer/SMPTProject/public/Lines/777.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 777,
    "lineName": "La Ronde",
    "from": "Station Bonaventure",
    "to": "La Ronde",
    "stops": {
        "1": "Station Bonaventure",
        "2": "de la Cathedrale / Saint-Jacques",
        "3": "Notre-Dame / Papineau",
        "4": "Papineau / Rene-Levesque",
        "5": "Papineau / Sainte-Catherine",
        "6": "Papineau / de Maisonneuve",
        "7": "La Ronde"
    }
}

=== Devitzer/SMPTProject/public/Lines/142.json
{
    "$schema": "./LineSchema.json",
    "frequent": true,
    "lineNumber": 142,
    "lineName": "Sauve",
    "from": "Gare Ahuntsic",
    "to": "Gare Saint-Michel-Montreal-Nord",
    "stops": {
        "1": "Gare Ahuntsic (de l'Acadie / Sauve)",
        "2": "Sauve / Meilleur",
        "3": "Sauve / Verville",
        "4": "Sauve / Tolhurst",
        "5": "Sauve / de l'Esplanade",
        "6": "Sauve / Saint-Urbain",
        "7": "Sauve / Saint-Laurent",
        "8": "Sauve / Laverdure",
        "9": "Station Sauve",
        "10": "Sauve / Lajeunesse",
        "11": "Sauve / Millen",
        "12": "Sauve / Saint-Hubert",
        "13": "Sauve / Saint-Charles",
        "14": "Sauve / de la Roche",
        "15": "Sauve / Christophe-Colomb",
        "16": "Sauve / Curotte",
        "17": "Sauve / Garnier",
        "18": "Sauve / Papineau",
        "19": "Sauve / Charton",
        "20": "Sauve / de Saint-Firmin",
        "21": "Sauve / Parthenais",
        "22": "Sauve / de Lille",
        "23": "Sauve / d'Iberville",
        "24": "Sauve / Sackville",
        "25": "Sauve / Larose",
        "26": "Sauve / Saint-Michel",
        "27": "Saint-Michel / Industriel",
        "28": "Industriel / du Parc-Georges",
        "29": "Industriel / Saint-Vital",
        "30": "Industriel / de Paris",
        "31": "Industriel / des Recollets",
        "32": "Gare Saint-Michel-Montreal-Nord"
    }
}

=== Devitzer/SMPTProject/public/Lines/440.json
{
    "$schema": "./LineSchema.json",
    "frequent": true,
    "lineNumber": 440,
    "lineName": "EXPRESS Pie-IX",
    "from": "Station Pie-IX",
    "to": "Marie-Victorin / No 7000",
    "stops": {
        "1": "Station Pie-IX",
        "2": "SRB Pie-IX / du Mont-Royal",
        "3": "SRB Pie-IX / Laurier",
        "4": "SRB Pie-IX / Rosemont",
        "5": "SRB Pie-IX / Beaubien",
        "6": "SRB Pie-IX / Belanger",
        "7": "SRB Pie-IX / Jean-Talon",
        "8": "SRB Pie-IX / Jarry",
        "9": "SRB Pie-IX / Robert",
        "10": "SRB Pie-IX / 39e Rue",
        "11": "SRB Pie-IX / 47e Rue",
        "12": "SRB Pie-IX / 56e Rue",
        "13": "SRB Pie-IX / Fleury",
        "14": "SRB Pie-IX / de Castille",
        "15": "SRB Pie-IX / d'Amos",
        "16": "Carrefour Henri-Bourassa / Pie-IX",
        "17": "Henri-Bourassa / Pelletier",
        "18": "Henri-Bourassa / Sainte-Gertrude",
        "19": "Henri-Bourassa / Salk",
        "20": "Henri-Bourassa / Sainte-Colette",
        "21": "CLSC de Montreal-Nord",
        "22": "Lacordaire / Crevier",
        "23": "Lacordaire / Maurice-Duplessis",
        "24": "Maurice-Duplessis / Desy",
        "25": "Maurice-Duplessis / Rolland",
        "26": "Maurice-Duplessis / Matte",
        "27": "Maurice-Duplessis / Langelier",
        "28": "Maurice-Duplessis / Albert-Hudon",
        "29": "Maurice-Duplessis / No 7000",
        "30": "Marie-Victorin / No 7000"
    }
}

=== Devitzer/SMPTProject/public/Lines/11.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 11,
    "lineName": "de la Verendrye",
    "from": "Lafleur / LaSalle",
    "to": "Station Jolicoeur",
    "stops": {
        "1": "Lafleur / LaSalle",
        "2": "LaSalle / Orchard",
        "3": "LaSalle / 90e Avenue",
        "4": "90e Avenue / Red Cross",
        "5": "90e Avenue / Airlie",
        "6": "Airlie / 80e Avenue",
        "7": "Airlie / 76e Avenue",
        "8": "de la Verendrye / Dollard",
        "9": "Dollard / Champlain",
        "10": "Champlain / 35e Avenue",
        "11": "Champlain / No 8398",
        "12": "Champlain / Raymond",
        "13": "Champlain / Gagne",
        "14": "Champlain / Bishop-Power",
        "15": "Bishop-Power / Bourdeau",
        "16": "Bourdeau / Jacqueline-Sicotte",
        "17": "Bourdeau / Therry",
        "18": "Bourdeau / Lapierre",
        "19": "Parc Angrignon",
        "20": "de la Verendrye / Trinitaires",
        "21": "Trinitaires / d'Aragon",
        "22": "Trinitaires / Jogues",
        "23": "Trinitaires / Lamont",
        "24": "Station Angrignon"
    }
}

=== Devitzer/SMPTProject/public/Lines/211.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 211,
    "lineName": "Pointe-Claire",
    "from": "Pierre Elliott Trudeau Intl Airport",
    "to": "Gare Baurepiere",
    "stops": {
        "1": "Pierre Elliott Trudeau Intl Airport",
        "2": "Albert de Niverville / Cardinal",
        "3": "Cardinal / Stuart-Graham",
        "4": "Cardinal / Thorncrest",
        "5": "Gare Pine Beach",
        "6": "Cardinal / Meadowvale",
        "7": "Cardinal / Avila-Legault",
        "8": "Cardinal / Neptune",
        "9": "Cardinal / Strathmore",
        "10": "Cardinal / des Sources",
        "11": "Cardinal / Chester",
        "12": "Donegani / King",
        "13": "Gare Valois",
        "14": "Donegani / Broadview",
        "15": "Donegani / Matland",
        "16": "Donegani / Michigan",
        "17": "Gare Pointe-Claire",
        "18": "Donegani / Terra-Cotta",
        "19": "Donegani / Maywood",
        "20": "Donegani / Eldorado",
        "21": "Donegani / Aurora",
        "22": "Aurora / Springdale",
        "23": "Aurora / Douglas-Shand",
        "24": "Aurora / Duke-of-Kent",
        "25": "Aurora / Sedgefield",
        "26": "Sedgefield / Saint-Jean",
        "27": "Saint-Jean / Hymus",
        "28": "Hymus / Alston",
        "29": "Hymus / Stillview",
        "30": "Hymus / Andre-Brunet",
        "31": "Hymus / Eaton",
        "32": "Hymus / Chateauneuf",
        "33": "Hymus / Caravelle",
        "34": "Hymus / Saint-Charles",
        "35": "Saint-Charles / Kirkland",
        "36": "Saint-Charles / No 2768",
        "37": "Saint-Charles / Creswell",
        "38": "Saint-Charles / Sherbrooke",
        "39": "Saint-Charles / Evergreen",
        "40": "Gare Beaconsfield",
        "41": "Elm / Allancroft",
        "42": "Elm / Park",
        "43": "Elm / Fairway",
        "44": "Elm / Shannon-Park",
        "45": "Elm / Montrose",
        "46": "Elm / Alice-Cartiere",
        "47": "Gare Baurepiere"
    }
}

=== Devitzer/SMPTProject/public/Lines/101.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 101,
    "lineName": "Nuns Island",
    "from": "Campus Bell",
    "to": "Andre-Prevost",
    "stops": {
        "1": "Campus Bell",
        "2": "de la Pointe Nord / Jacques-Le-Ber",
        "3": "Station REM Ile-Des-Soeurs",
        "4": "Rene-Levesque / Champlain",
        "5": "Rene-Levesque / Levert",
        "6": "Rene-Levesque / du Commerce",
        "7": "du Commerce / Cite-de-l'Ile",
        "8": "du Commerce / Provigo",
        "9": "du Golf / No 210",
        "10": "du Golf / Camelias",
        "11": "du Golf / William-Paul",
        "12": "du Golf / Roland-Jeanneau",
        "13": "Marguerite-Bourgeoys / du Club Marin",
        "14": "Marguerite-Bourgeoys / de la Foret",
        "15": "Marguerite-Bourgeoys / de l'Ile-des-Soeurs",
        "16": "de l'Ile-des-Soeurs / Berlioz",
        "17": "de l'Ile-des-Soeurs / Corot",
        "18": "de l'Ile-des-Soeurs / Darwin",
        "19": "de l'Ile-des-Soeurs / Elgar",
        "20": "de l'Ile-des-Soeurs / de Gaspe",
        "21": "de l'Ile-des-Soeurs / Hall",
        "22": "de la Pointe Sud / Des Sommets",
        "23": "de la Pointe Sud / Parulines",
        "24": "de la Pointe Sud / No 250",
        "25": "de la Pointe Sud / Andre-Prevost",
        "26": "Andre-Prevost / Serge-Garant E",
        "27": "Andre-Prevost / Serge-Garant O"
    }
}

=== Devitzer/SMPTProject/public/Lines/72.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 72,
    "lineName": "de Lorimier",
    "from": "Station Papineau",
    "to": "Station Saint-Michel",
    "stops": {
        "1": "Station Papineau",
        "2": "de Maisonneuve / Papineau",
        "3": "Sainte-Catherine / de Lorimier",
        "4": "de Lorimier / de Maisonneuve",
        "5": "de Lorimier / Ontario",
        "6": "de Lorimier / de Rouen",
        "7": "de Lorimier / Sherbrooke",
        "8": "de Lorimier / Gauthier",
        "9": "de Lorimier / Rachel",
        "10": "de Lorimier / Marie-Anne",
        "11": "de Lorimier / du Mont-Royal",
        "12": "de Lorimier / Gilford",
        "13": "de Lorimier / Saint-Joseph",
        "14": "de Lorimier / Laurier",
        "15": "de Lorimier / Masson",
        "16": "de Lorimier / Holt",
        "17": "de Lorimier / Rosemont",
        "18": "de Lorimier / de Bellechasse",
        "19": "de Lorimier / Beaubien",
        "20": "de Lorimier / Saint-Zotique",
        "21": "de Lorimier / Belanger",
        "22": "de Lorimier / Jean-Talon",
        "23": "de Lorimier / Everett",
        "24": "de Lorimier / Villeray",
        "25": "de Lorimier / Tillemont",
        "26": "de Lorimier / Jarry",
        "27": "Cremazie / des Ecores",
        "28": "Cremazie / d'Iberville",
        "29": "Cremazie / 2e Avenue",
        "30": "Cremazie / 8e Avenue",
        "31": "Cremazie / Saint-Michel",
        "32" :"Saint-Michel / Villeray",
        "33": "Station Saint-Michel"
    }
}
