=== Devitzer/SMPTProject/public/Lines/LineSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["lineNumber", "lineName", "from", "to", "stops"],
    "properties": {
      "frequent": {
        "type": "boolean"
      },
      "lineNumber": {
        "type": "integer"
      },
      "lineName": {
        "type": "string"
      },
      "from": {
        "type": "string"
      },
      "to": {
        "type": "string"
      },
      "express": {
        "type": "boolean"
      },
      "ooi-express": {
        "type": "boolean"
      },
      "stops": {
        "type": "object",
        "minProperties": 1,
        "additionalProperties": {
          "type": "string"
        }
      }
    }
  }

=== Devitzer/SMPTProject/public/Lines/901.json
{
    "$schema": "./LineSchema.json",
    "ooi-express": true,
    "frequent": false,
    "lineNumber": 901,
    "lineName": "EXPRESS Laval",
    "from": "Gare Centrale",
    "to": "Gare Vimont",
    "stops": {
        "1": "Gare Centrale",
        "2": "Mansfield / Rene-Levesque",
        "3": "Rene-Levesque / Peel",
        "4": "Rene-Levesque / Drummond",
        "5": "Rene-Levesque / de la Montagne",
        "6": "Rene-Levesque / Lucien-L'Allier",
        "7": "Rene-Levesque / Guy",
        "8": "Rene-Levesque / Saint-Mathieu",
        "9": "Rene-Levesque / Fort",
        "10": "Rene-Levesque / Atwater",
        "11": "Dorchester / Greene",
        "12": "Dorchester / Sainte-Catherine",
        "13": "Sainte-Catherine / Kensington",
        "14": "Sainte-Catherine / Melville",
        "15": "Sainte-Catherine / Lansdowne",
        "16": "Sainte-Catherine / Victoria",
        "17": "Sainte-Catherine / de Maisonneuve",
        "18": "Station Vendome",
        "19": "de Maissoneuve / Decarie",
        "20": "Decarie / Sherbrooke",
        "21": "Sherbrooke / Autoroute 15",
        "22": "de la Concorde / le Corbusier",
        "23": "Station Montmorency",
        "24": "de l'Avenir / de la Concorde",
        "25": "de la Concorde / Laval",
        "26": "Laval / Dube",
        "27": "Laval / des Pres",
        "28": "Laval / du Souvenir",
        "29": "Laval / du Trait-Carre",
        "30": "Laval / Jolivet",
        "31": "Laval / No 1700",
        "32": "Laval / Saint-Martin",
        "33": "Industriel / Salaberry",
        "34": "Industriel / Lippmann",
        "35": "Industriel / Munck",
        "36": "Industriel / Cunard",
        "37": "Industriel / Berlier",
        "38": "Industriel / Saint-Elzear",
        "39": "Industriel / Bergar",
        "40": "Industriel / Dagenais",
        "41": "Dagenais / Francis-Hughes",
        "42": "Gare Vimont"
    }
}

=== Devitzer/SMPTProject/public/Lines/125.json
{
    "$schema": "./LineSchema.json",
    "frequent": true,
    "lineNumber": 125,
    "lineName": "Beaubien",
    "from": "Station Beaubien",
    "to": "Galeries d'Anjou",
    "stops": {
        "1": "Station Beaubien",
        "2": "Beaubien / Saint-Hubert",
        "3": "Beaubien / Christophe-Colomb",
        "4": "Beaubien / de Normanville",
        "5": "Beaubien / Lanaudiere",
        "6": "Beaubien / Fabre",
        "7": "Beaubien / Papineau",
        "8": "Beaubien / Chabot",
        "9": "Beaubien / de Lorimier",
        "10": "Beaubien / Louis-Hemon",
        "11": "Beaubien / d'Iberville",
        "12": "Beaubien / 1e Avenue",
        "13": "Beaubien / 6e Avenue",
        "14": "Beaubien / Saint-Michel",
        "15": "Beaubien / 13e Avenue",
        "16": "Beaubien / 16e Avenue",
        "17": "Beaubien / 18e Avenue",
        "18": "Beaubien / 20e Avenue",
        "19": "Beaubien / Pie-IX",
        "20": "Beaubien / 24e Avenue",
        "21": "Beaubien / 26e Avenue",
        "22": "Beaubien / 28e Avenue",
        "23": "Beaubien / 31e Avenue",
        "24": "Beaubien / 33e Avenue",
        "25": "Beaubien / 35e Avenue",
        "26": "Beaubien / Viau",
        "27": "Beaubien / 39e Avenue",
        "28": "Beaubien / 41e Avenue",
        "29": "Beaubien / 43e Avenue",
        "30": "Beaubien / Assomption",
        "31": "Beaubien / Chatelain",
        "32": "Beaubien / de Pontoise",
        "33": "Beaubien / Lacordaire",
        "34": "Beaubien / Place Beaubien",
        "35": "Beaubien / Albani",
        "36": "Beaubien / de Carignan",
        "37": "Beaubien / Langelier",
        "38": "Beaubien / Francois-Boivin",
        "39": "Beaubien / Pierre-Gadois",
        "40": "Beaubien / des Galeries-d'Anjou",
        "41": "des Galeries-d'Anjou / Saint-Zotique",
        "42": "des Galeries-d'Anjou / Belanger",
        "43": "Galeries d'Anjou"
    }
}

=== Devitzer/SMPTProject/public/Lines/52.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 52,
    "lineName": "Rene-Levesque",
    "from": "Ouest Ville Marie (Sherbrooke / Clarke)",
    "to": "Station Frontenac",
    "stops": {
        "1": "Sherbrooke / Clarke",
        "2": "Clarke / De Maisonneuve",
        "3": "Clarke / Saint-Catherine",
        "4": "Dorchester / Greene",
        "5": "Dorchester / Clandeboye",
        "6": "Dorchester / Atwater",
        "7": "Rene-Levesque / du Sussex",
        "8": "Rene-Levesque / Fort",
        "9": "Rene-Levesque / St Marc",
        "10": "Rene-Levesque / Guy",
        "11": "Rene-Levesque / Bishop",
        "12": "Rene-Levesque / de la Montagne",
        "13": "Rene-Levesque / Peel",
        "14": "Rene-Levesque / Mansfield",
        "15": "Rene-Levesque / Robert-Bourassa",
        "16": "Rene-Levesque / Beaver Hall",
        "17": "Rene-Levesque / de Bleury",
        "18": "Rene-Levesque / Saint-Urbain",
        "19": "Rene-Levesque / St-Laurent",
        "20": "Rene-Levesque / De Bullion",
        "21": "Rene-Levesque / Sanguinet",
        "22": "Rene-Levesque / Saint Denis",
        "23": "Rene-Levesque / Berri",
        "24": "Rene-Levesque / St-Hubert",
        "25": "Rene-Levesque / St Andre",
        "26": "Rene-Levesque / Wolfe",
        "27": "Rene-Levesque / Visitation",
        "28": "Rene-Levesque / Plessis",
        "29": "Rene-Levesque / Papineau",
        "30": "Rene-Levesque / De Lorimier",
        "31": "De Lorimier / Notre-Dame",
        "32": "Notre-Dame / Frontenac",
        "33": "Frontenac / de Maisonneuve",
        "34": "Frontenac / la Fontaine",
        "35": "Station Frontenac"
    }
}

=== Devitzer/SMPTProject/public/Lines/23.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 23,
    "lineName": "Westminster",
    "from": "Ecole Secondaire Bialik",
    "to": "Station Villa-Maria",
    "stops": {
        "1": "Ecole Secondaire Bialik",
        "2": "Kildare / Merrimac",
        "3": "Kildare / Rembrandt",
        "4": "Kildare / Cavendish",
        "5": "Kildare / Kellert",
        "6": "Kildare / Einstein",
        "7": "Kildare / Caldwell",
        "8": "Kildare / Trinity",
        "9": "Kildare / Melling",
        "10": "Kildare / Leger",
        "11": "Kildare / McAlear",
        "12": "Kildare / Westminster",
        "13": "Westminster / Guelph",
        "14": "Westminster / Cote-Saint-Luc",
        "15": "Westminster / Westover",
        "16": "Westminster / Radcliffe",
        "17": "Westminster / Parkside",
        "18": "Westminster / Nelson",
        "19": "Westminster / Curzon",
        "20": "Sherbrooke / Brock",
        "21": "Gare Montreal West",
        "22": "Sherbrooke / West Broadway",
        "23": "Monkland / Mayfair",
        "24": "Monkland / Rosedale",
        "25": "Monkland / Montclair",
        "26": "Monkland / Walkley",
        "27": "Monkland / Cavendish",
        "28": "Monkland / Benny",
        "29": "Monkland / Madison",
        "30": "Monkland / Grand Blvd",
        "31": "Monkland / Hingston",
        "32": "Monkland / Royal",
        "33": "Monkland / Melrose",
        "34": "Monkland / Harvard",
        "35": "Monkland / Marcil",
        "36": "Monkland / Girouard",
        "37": "Station Villa-Maria"
    }
}

=== Devitzer/SMPTProject/public/Lines/123.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 123,
    "lineName": "Maurice-Duplessis",
    "from": "Gare Anjou",
    "to": "Gare Pointe-aux-Trembles",
    "stops": {
        "1": "Gare Anjou",
        "2": "6e Avenue / Henri-Bourassa",
        "3": "Louis.-H.-Lafontaine / Arthur-Leveille",
        "4": "Louis.-H.-Lafontaine / Maurice-Duplessis",
        "5": "Maurice-Duplessis / 5e Avenue",
        "6": "Maurice-Duplessis / Pierre-Blanchet",
        "7": "Maurice-Duplessis / Gilbert-Barbier",
        "8": "Maurice-Duplessis / Marc-Aurele-Fortin",
        "9": "Maurice-Duplessis / Fernand-Gauthier",
        "10": "Maurice-Duplessis / la Valiniere",
        "11": "Maurice-Duplessis / Camille-Tessier",
        "12": "Maurice-Duplessis / Dom-Bellot",
        "13": "Maurice-Duplessis / Armand-Bombardier",
        "14": "Maurice-Duplessis / Clement-Ader",
        "15": "Maurice-Duplessis / 27e Avenue",
        "16": "Maurice-Duplessis / Eva-Circe",
        "17": "Maurice-Duplessis / Andre-Dumas",
        "18": "Maurice-Duplessis / Rita-Levi-Montalcini",
        "19": "Maurice-Duplessis / Pierre-Baillargeon",
        "20": "Maurice-Duplessis / 41e Avenue",
        "21": "Maurice-Duplessis / Rodolphe-Forget",
        "22": "Maurice-Duplessis / J.-J.-Joubert",
        "23": "Maurice-Duplessis / Jean-Yves-Bigras",
        "24": "Maurice-Duplessis / 54e Avenue",
        "25": "Maurice-Duplessis / 57e Avenue",
        "26": "Maurice-Duplessis / Riviere-des-Prairies",
        "27": "Maurice-Duplessis / 63e Avenue",
        "28": "Maurice-Duplessis / 70e Avenue",
        "29": "Maurice-Duplessis / Olivier-Lejeune",
        "30": "Maurice-Duplessis / Saint-Jean-Baptiste",
        "31": "Gare Riviere-des-Prairies",
        "32": "Maurice-Duplessis / 86e Avenue",
        "33": "Maurice-Duplessis / Armand-Chaput",
        "34": "Armand-Chaput / No 11410",
        "35": "Armand-Chaput / No 11380",
        "36": "Armand-Chaput / Henri-Bourassa",
        "37": "Henri-Bourassa / 36e Avenue",
        "38": "Henri-Bourassa / 40e Avenue",
        "39": "Henri-Bourassa / Sherbrooke",
        "40": "Sherbrooke / 47e Avenue",
        "41": "Sherbrooke / de la Rousseliere",
        "42": "Sherbrooke / 53e Avenue",
        "43": "Gare Pointe-aux-Trembles"
    }
}

=== Devitzer/SMPTProject/public/Lines/702.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 702,
    "lineName": "Victoria",
    "from": "Gare Montreal-Ouest",
    "to": "Pierre Elliott Trudeau Intl Airport",
    "stops": {
        "1": "Gare Montreal-Ouest",
        "2": "Sherbrooke / Westminster",
        "3": "Westminster / Avon",
        "4": "Avon / Milton",
        "5": "Saint-Jacques / Ouellette",
        "6": "Saint-Jacques / Saint-Pierre",
        "7": "Saint-Jacques / Victoria",
        "8": "Victoria / George-V",
        "9": "Victoria / 2e Avenue",
        "10": "Victoria / 4e Avenue",
        "11": "Victoria / 6e Avenue",
        "12": "Victoria / 10e Avenue",
        "13": "Victoria / 16e Avenue",
        "14": "Victoria / 18e Avenue",
        "15": "Victoria / 21e Avenue",
        "16": "Victoria / 28e Avenue",
        "17": "Victoria / 32e Avenue",
        "18": "Victoria / Saint-Antoine",
        "19": "Victoria / 40e Avenue",
        "20": "Victoria / 43e Avenue",
        "21": "Victoria / Provost",
        "22": "Victoria / 48e Avenue",
        "23": "Victoria / 50e Avenue",
        "24": "Victoria / Meadowbrook",
        "25": "Victoria / 55e Avenue",
        "26": "Bouchard / Galland",
        "27": "Bouchard / Mousseau-Vermette",
        "28": "Bouchard / Martin",
        "29": "Cardinal / Albert de Niverville",
        "30": "Albert de Niverville / Romeo Vachon",
        "31": "Pierre Elliott Trudeau Intl Airport"
    }
}

=== Devitzer/SMPTProject/public/Lines/130.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 130,
    "lineName": "de Verdun",
    "from": "Station Angrignon",
    "to": "Station Berri-UQAM",
    "stops": {
        "1": "Station Angrignon",
        "2": "Trinitaires / Lacroix",
        "3": "Trinitaires / Jogues",
        "4": "Trinitaires / Hurteau",
        "5": "Trinitaires / d'Aragon",
        "6": "Trinitaires / de la Verendrye",
        "7": "de la Verendrye / Stephens",
        "8": "Stephens / No 1482",
        "9": "Stephens / Beurling",
        "10": "Stephens / Monteith",
        "11": "Stephens / LaSalle",
        "12": "LaSalle / Valiquette",
        "13": "LaSalle / Godin",
        "14": "de Verdun / Richard",
        "15": "de Verdun / Moffat",
        "16": "de Verdun / Osborne",
        "17": "de Verdun / Woodland",
        "18": "de Verdun / Desmarchais",
        "19": "de Verdun / 5e Avenue",
        "20": "de Verdun / 2e Avenue",
        "21": "Station Verdun",
        "22": "de Verdun / Rielle",
        "23": "de Verdun / Galt",
        "24": "de Verdun / Hickson",
        "25": "de Verdun / Regina",
        "26": "de Verdun / Strathmore",
        "27": "de Verdun / Caisse",
        "28": "de Verdun / Atwater",
        "29": "Atwater / Notre-Dame",
        "30": "Station Lionel-Groulx",
        "31": "Atwater / Saint-Antoine",
        "32": "Atwater / Rene-Levesque",
        "33": "Rene-Levesque / Fort",
        "34": "Rene-Levesque / Guy",
        "35": "Rene-Levesque / Lucien-L'Allier",
        "36": "Rene-Levesque / Drummond",
        "37": "Rene-Levesque / Peel",
        "38": "Rene-Levesque / Mansfield",
        "39": "Rene-Levesque / Robert-Bourassa",
        "40": "Rene-Levesque / Beaver Hall",
        "41": "Rene-Levesque / Saint-Alexander",
        "42": "Rene-Levesque / de Bleury",
        "43": "Complex Guy-Favreau",
        "44": "Rene-Levesque / Saint-Urbain",
        "45": "Rene-Levesque / Saint-Laurent",
        "46": "Rene-Levesque / de Bullion",
        "47": "Rene-Levesque / Sanguinet",
        "48": "Rene-Levesque / Saint-Denis",
        "49": "Rene-Levesque / Berri",
        "50": "Station Berri-UQAM"
    }
}

=== Devitzer/SMPTProject/public/Lines/747.json
{
    "$schema": "./LineSchema.json",
    "frequent": true,
    "lineNumber": 747,
    "lineName": "Airport via Ville-Marie",
    "from": "Ville-Marie",
    "to": "Pierre Elliott Trudeau Intl Airport",
    "stops": {
        "1": "Gare Centrale",
        "2": "Mansfield / Rene-Levesque",
        "3": "Rene-Levesque / Peel",
        "4": "Rene-Levesque / Drummond",
        "5": "Rene-Levesque / de la Montagne",
        "6": "Rene-Levesque / Lucien-L'Allier",
        "7": "Pierre Elliott Trudeau Intl Airport"
    }
}
