=== Devitzer/SMPTProject/public/Lines/LineSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["lineNumber", "lineName", "from", "to", "stops"],
    "properties": {
      "frequent": {
        "type": "boolean"
      },
      "lineNumber": {
        "type": "integer"
      },
      "lineName": {
        "type": "string"
      },
      "from": {
        "type": "string"
      },
      "to": {
        "type": "string"
      },
      "express": {
        "type": "boolean"
      },
      "ooi-express": {
        "type": "boolean"
      },
      "stops": {
        "type": "object",
        "minProperties": 1,
        "additionalProperties": {
          "type": "string"
        }
      }
    }
  }

=== Devitzer/SMPTProject/public/Lines/103.json
{
    "$schema": "./LineSchema.json",
    "frequent": true,
    "lineNumber": 103,
    "lineName": "Parc Industriel-Lachine",
    "from": "Terminus Saint-Pierre",
    "to": "Station Cote-Vertu",
    "stops": {
        "1": "Terminus Saint-Pierre",
        "2": "Saint-Jacques / Ouellette",
        "3": "Saint-Jacques / du Chalet",
        "4": "Saint-Jacques / Saint-Pierre",
        "5": "Saint-Jacques / Richardson",
        "6": "Saint-Jacques / Victoria",
        "7": "Victoria / 1e Avenue",
        "8": "1e Avenue / Saint-Antoine",
        "9": "1e Avenue / Provost",
        "10": "Provost / 3e Avenue",
        "11": "Provost / 5e Avenue",
        "12": "Provost / 7e Avenue",
        "13": "Provost / 9e Avenue",
        "14": "Provost / 11e Avenue",
        "15": "Provost / 13e Avenue",
        "16": "Provost / 16e Avenue",
        "17": "Provost / Esther-Blondin",
        "18": "Provost / 20e Avenue",
        "19": "Provost / 24e Avenue",
        "20": "Provost / 26e Avenue",
        "21": "Provost / 32e Avenue",
        "22": "Provost / 36e Avenue",
        "23": "Provost / 37e Avenue",
        "24": "Provost / 39e Avenue",
        "25": "Provost / 42e Avenue",
        "26": "Provost / 44e Avenue",
        "27": "Provost / Victoria",
        "28": "Victoria / 48e Avenue",
        "29": "Victoria / 50e Avenue",
        "30": "Victoria / Meadowbrook",
        "31": "Victoria / 52e Avenue",
        "32": "Victoria / 55e Avenue",
        "33": "55e Avenue / No 920",
        "34": "55e Avenue / No 1200",
        "35": "55e Avenue / Fairway",
        "36": "Fairway / 52e Avenue",
        "37": "Fairway / 50e Avenue",
        "38": "Fairway / 46e Avenue",
        "39": "Fairway / Francois-Lenoir",
        "40": "Fairway / 32e Avenue",
        "41": "32e Avenue / Jean-Baptiste-Deschamps",
        "42": "Jean-Baptiste-Deschamps / No 3245",
        "43": "Jean-Baptiste-Deschamps / Courval",
        "44": "Jean-Baptiste-Deschamps / No 2605",
        "45": "Jean-Baptiste-Deschamps / Hickmore",
        "46": "Hickmore / Courval",
        "47": "Hickmore / Montee de Liesse",
        "48": "Montee de Liesse / Hickmore",
        "49": "Montee de Liesse / No 110",
        "50": "Montee de Liesse / Bourg",
        "51": "Montee de Liesse / Cote-de-Liesse",
        "52": "Montee de Liesse / No 222",
        "53": "Montee de Liesse / No 360",
        "54": "Montee de Liesse / Reverchon",
        "55": "Montee de Liesse / No 750",
        "56": "Montee de Liesse / McCaffrey",
        "57": "Montee de Liesse / Cote-Vertu",
        "58": "Cote-Vertu / Begin",
        "59": "Cote-Vertu / No 3695",
        "60": "Cote-Vertu / Beaulac",
        "61": "Cote-Vertu / No 3200",
        "62": "Cote-Vertu / Cavendish",
        "63": "Cote-Vertu / Hocquart",
        "64": "Cote-Vertu / Bertrand",
        "65": "Cote-Vertu / Alexis-Nihon",
        "66": "Cote-Vertu / Saint-Aubin",
        "67": "Cote-Vertu / Marcel-Laurin",
        "68": "Cote-Vertu / Leduc",
        "69": "Cote-Vertu / Crevier",
        "70": "Station Cote-Vertu"
    }

}

=== Devitzer/SMPTProject/public/Lines/54.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 54,
    "lineName": "Saint-Michel",
    "from": "Station Henri-Bourassa",
    "to": "Station Pie-IX",
    "stops": {
        "1": "Station Henri-Bourassa",
        "2": "Henri-Bourassa / Saint-Hubert",
        "3": "Henri-Bourassa / Saint-Charles",
        "4": "Henri-Bourassa / de la Roche",
        "5": "Henri-Bourassa / Christophe-Colomb",
        "6": "Henri-Bourassa / Hamel",
        "7": "Henri-Bourassa / Francis",
        "8": "Henri-Bourassa / Tache",
        "9": "Henri-Bourassa / Papineau",
        "10": "Henri-Bourassa / Hamelin",
        "11": "Henri-Bourassa / De Lorimier",
        "12": "Henri-Bourassa / Parthenais",
        "13": "Henri-Bourassa / Rancourt",
        "14": "Henri-Bourassa / Bruchesi",
        "15": "Henri-Bourassa / Andre-Jobin",
        "16": "Henri-Bourassa / Vianney",
        "17": "Henri-Bourassa / J-J-Gagnier",
        "18": "Henri-Bourassa / Saint-Michel",
        "19": "Saint-Michel / Prieur",
        "20": "Saint-Michel / Fleury",
        "21": "Saint-Michel / de Mont-Joli",
        "22": "Saint-Michel / Industriel",
        "23": "Saint-Michel / Champdore",
        "24": "Saint-Michel / Louvain",
        "25": "Saint-Michel / Legendre",
        "26": "Saint-Michel / Emile-Journault",
        "27": "Saint-Michel / Denis-Papin",
        "28": "Saint-Michel / Robert",
        "29": "Saint-Michel / Deville",
        "30": "Saint-Michel / d'Herelle",
        "31": "Saint-Michel / Jarry",
        "32": "Station Saint-Michel",
        "33": "Saint-Michel / Jean-Talon",
        "34": "Jean-Talon / 12e Avenue",
        "35": "Jean-Talon / Musset",
        "36": "Jean-Talon / 15e Avenue",
        "37": "Jean-Talon / 17e Avenue",
        "38": "Jean-Talon / 18e Avenue",
        "39": "Jean-Talon / 20e Avenue",
        "40": "Jean-Talon / Pie-IX",
        "41": "Pie-IX / Belanger",
        "42": "Pie-IX / Saint-Zotique",
        "43": "Pie-IX / Beaubien",
        "44": "Pie-IX / Rosemont",
        "45": "Pie-IX / Dandurand",
        "46": "Pie-IX / Masson",
        "47": "Pie-IX / Laurier",
        "48": "Pie-IX / Saint-Joseph",
        "49": "Pie-IX / Mont-Royal",
        "50": "Pie-IX / Sherbrooke",
        "51": "Station Pie-IX"
    }
}

=== Devitzer/SMPTProject/public/Lines/204.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 204,
    "lineName": "Dollard-Des-Ormeaux",
    "from": "Gare Pointe-Claire",
    "to": "Gare Sunnybrooke",
    "stops": {
        "1": "Gare Pointe-Claire",
        "2": "Donegani / Terra-Cotta",
        "3": "Donegani / Maywood",
        "4": "Donegani / Eldorado",
        "5": "Donegani / Aurora",
        "6": "Aurora / Springdale",
        "7": "Aurora / Douglas-Shrand",
        "8": "Douglas-Shand / Saint-Jean",
        "9": "Saint-Jean / Duke-of-Kent",
        "10": "Saint-Jean / Sedgefield",
        "11": "Saint-Jean / Chaucer",
        "12": "Saint-Jean / Hymus",
        "13": "Saint-Jean / Holiday",
        "14": "Saint-Jean / Brunswick",
        "15": "Saint-Jean / Labrosse",
        "16": "Saint-Jean / Blue-Haven",
        "17": "Saint-Jean / Salaberry",
        "18": "Saint-Jean / Lake",
        "19": "Saint-Jean / Roger-Pilon",
        "20": "Roger-Pilon / Barnett",
        "21": "Roger-Pilon / Mirabel",
        "22": "Roger-Pilon / Armstrong",
        "23": "Roger-Pilon / Baffin",
        "24": "Roger-Pilon / Tecumseh",
        "25": "Roger-Pilon / Fredmir",
        "26": "Roger-Pilon / Manuel",
        "27": "Roger-Pilon / Westpark",
        "28": "Roger-Pilon / Dephoure",
        "29": "Roger-Pilon / Canterbury",
        "30": "Roger-Pilon / Merritt",
        "31": "Roger-Pilon / des Sources",
        "32": "des Sources / 14e Avenue",
        "33": "des Sources / 9e Avenue",
        "34": "des Sources / Anselme-Lavigne",
        "35": "des Sources / Ross",
        "36": "des Sources / Pierrefonds",
        "37": "des Sources / Gouin",
        "38": "Gouin / Pierrefonds",
        "39": "Gouin / 8e Avenue",
        "40": "Gouin / Meighen",
        "41": "Gouin / 3e Avenue",
        "42": "Gouin / 1e Avenue",
        "43": "Gouin / Lalande",
        "44": "Gouin / 2e Rue",
        "45": "Gouin / 1e Rue",
        "46": "Gouin / Dollard",
        "47": "Gouin / Deslauriers",
        "48": "Gare Sunnybrooke"
    }
}

=== Devitzer/SMPTProject/public/Lines/248.json
{
    "$schema": "./LineSchema.json",
    "frequent": true,
    "lineNumber": 248,
    "lineName": "Gouin Est",
    "from": "Henri-Bourassa",
    "to": "Plage-de-l'Est",
    "stops": {
        "1": "Station Henri-Bourassa",
        "2": "Henri-Bourassa / Saint-Hubert",
        "3": "Henri-Bourassa / Saint-Charles",
        "4": "Henri-Bourassa / de la Roche",
        "5": "Henri-Bourassa / Christophe-Colomb",
        "6": "Henri-Bourassa / Hamel",
        "7": "Henri-Bourassa / Francis",
        "8": "Henri-Bourassa / Tache",
        "9": "Henri-Bourassa / Papineau",
        "10": "Henri-Bourassa / Hamelin",
        "11": "Henri-Bourassa / De Lorimier",
        "12": "Henri-Bourassa / Parthenais",
        "13": "Henri-Bourassa / Rancourt",
        "14": "Henri-Bourassa / Bruchesi",
        "15": "Henri-Bourassa / Andre-Jobin",
        "16": "Henri-Bourassa / Vianney",
        "17": "Henri-Bourassa / J-J-Gagnier",
        "18": "Henri-Bourassa / Saint-Michel",
        "19": "Saint-Michel / Gouin",
        "20": "Gouin / Mackay",
        "21": "Gouin / Audoin",
        "22": "Gouin / Leblanc",
        "23": "Gouin / Lausanne",
        "24": "Gouin / de Mere-Anselme",
        "25": "Gouin / des Laurentides",
        "26": "Gouin / de Bruxelles",
        "27": "Gouin / Plaza",
        "28": "Gouin / de London",
        "29": "Gouin / Gariepy",
        "30": "Gouin / Saint-Julien",
        "31": "Gouin / de l'Hotel-de-Ville",
        "32": "Gouin / Pelletier",
        "33": "Gouin / Balzac",
        "34": "Gouin / Ethier",
        "35": "Gouin / Pigeon",
        "36": "Gouin / Sainte-Gertrude",
        "37": "Gouin / Desaulniers",
        "38": "Gouin / Brunet",
        "39": "Gouin / Alfred",
        "40": "Gouin / Salk",
        "41": "Gouin / Lanthier",
        "42": "Gouin / Lacordaire",
        "43": "Gouin / Hector-Lamarre",
        "44": "Gouin / Robert",
        "45": "Gouin / Corbeil",
        "46": "Gouin / Veuillot",
        "47": "Gouin / Langelier",
        "48": "Langelier / Leger",
        "49": "Leger / Albert-Hudon",
        "50": "Perras / 4e Avenue",
        "51": "Perras / Pierre-Blanchet",
        "52": "Perras / Gilbert-Barbier",
        "53": "Perras / Aurele-Fortin",
        "54": "Perras / Fernand-Gauthier",
        "55": "Perras / Elle Beauregard",
        "56": "Perras / Salomon-Marion",
        "57": "Perras / Armand-Bombardier",
        "58": "24e Avenue / Gouin",
        "59": "Gouin / 27e Avenue",
        "60": "Gouin / Paul-Dufault",
        "61": "Parc Pierre-Perrault",
        "62": "Gouin / Rita-Levi-Montalcini",
        "63": "Gouin / 39e Avenue",
        "64": "Gouin / 41e Avenue",
        "65": "Gouin / Rodolphe-Forget",
        "66": "Gouin / 48e Avenue",
        "67": "Gouin / 52e Avenue",
        "68": "Gouin / 54e Avenue",
        "69": "Gouin / 56e Avenue",
        "70": "Gouin / Riviere-des-Prairies",
        "71": "Parc Zotique-Saint-Jean",
        "72": "Gouin / 64e Avenue",
        "73": "Gouin / 66e Avenue",
        "74": "Gouin / 71e Avenue",
        "75": "Gouin / Francois-Huot",
        "76": "Gouin / d'Alembert",
        "77": "Gouin / Saint-Jean-Baptiste",
        "78": "Gouin / Cageux Park",
        "79": "Gouin / 89e Avenue",
        "80": "Gouin / 94e Avenue",
        "81": "Parc Ile Haynes",
        "82": "Gouin / 133e Avenue",
        "83": "Gouin / Prince Arthur",
        "84": "Gouin / Sherbrooke",
        "85": "Sherbrooke / Notre-Dame",
        "86": "Notre-Dame / Sainte-Maria-Goretti",
        "87": "Plage-de-l'Est"
    }
}

=== Devitzer/SMPTProject/public/Lines/13.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 13,
    "lineName": "La Ronde via Bd LaSalle",
    "from": "Ecluse de Lachine",
    "to": "La Ronde",
    "stops": {
        "1": "Ecluse de Lachine (Saint Patrick / du Musee)",
        "2": "du Musee / Lyette",
        "3": "LaSalle / Av Dupras",
        "4": "LaSalle / Av Strathyre",
        "5": "LaSalle / Highlands (Gare LaSalle)",
        "6": "LaSalle / des Oblats",
        "7": "LaSalle / du Tresor Cache",
        "8": "LaSalle / Av Lafleur",
        "9": "LaSalle / Av Orchard",
        "10": "LaSalle / 90e Avenue",
        "11": "LaSalle / Av. 80e",
        "12": "LaSalle / 75e Avenue",
        "13": "LaSalle / 68e Avenue",
        "14": "LaSalle / 66e Avenue",
        "15": "LaSalle / Champlain Blvd",
        "16": "LaSalle / 43e Avenue",
        "17": "LaSalle / 37e Avenue",
        "18": "LaSalle / Raymond",
        "19": "LaSalle / Gagne",
        "20": "LaSalle / Bd Bishop-Power",
        "21": "LaSalle / 8e Ave",
        "22": "LaSalle / 6e Ave",
        "23": "LaSalle / 4e Ave",
        "24": "LaSalle / 2e Ave",
        "25": "LaSalle / Av Alepin",
        "26": "LaSalle / Av Lacharite",
        "27": "LaSalle / Av Senecal",
        "28": "LaSalle / Fayolle",
        "29": "LaSalle / Clemenceau",
        "30": "LaSalle / Crawford",
        "31": "LaSalle / Leclair",
        "32": "LaSalle / No 6875",
        "33": "LaSalle / Bannantyne",
        "34": "LaSalle / Rolland",
        "35": "LaSalle / Valiquette",
        "36": "LaSalle / Ave Riverview",
        "37": "LaSalle / Brault",
        "38": "LaSalle / Manning",
        "39": "LaSalle / Beatty (Wellington)",
        "40": "LaSalle / Woodland",
        "41": "LaSalle / Desmarchais Blvd",
        "42": "LaSalle / 5e Avenue",
        "43": "LaSalle / 4e Avenue",
        "44": "LaSalle / 3e Avenue",
        "45": "LaSalle / 1ere Avenue",
        "46": "LaSalle / Rielle",
        "47": "LaSalle / Galt et de l'Eglise",
        "48": "LaSalle / Hickson",
        "49": "LaSalle / Wellington",
        "50": "Wellington / Gilberte-Dube",
        "51": "Wellington / Butler",
        "52": "Wellington / Charlevoix",
        "53": "Parc Marguerite Bourgeoys",
        "54": "Wellington / Fortune",
        "55": "Wellington / Charon",
        "56": "Wellington / Ste Madeleine",
        "57": "Wellington / de la Congregation",
        "58": "Wellington / Mullins",
        "59": "Wellington / Centre",
        "60": "Wellington / Bridge",
        "61": "Bridge / Mill",
        "62": "Pierre-Dupuy / Des Moulins",
        "63": "Pierre-Dupuy / Habitat 67",
        "64": "La Ronde"
    }
}

=== Devitzer/SMPTProject/public/Lines/129.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 129,
    "lineName": "Saint-Jean-Baptiste",
    "from": "Sherbrooke / du Tricentenaire",
    "to": "Gare Riviere-des-Prairies",
    "stops": {
        "1": "Sherbrooke / du Tricentenaire",
        "2": "du Tricentenaire / Forsyth",
        "3": "du Tricentenaire / de Montigny",
        "4": "du Tricentenaire / Joseph-d'Argent",
        "5": "du Tricentenaire / Rene-Levesque",
        "6": "du Tricentenaire / Victoria",
        "7": "du Tricentenaire / Notre-Dame",
        "8": "Notre-Dame / No 12625",
        "9": "Notre-Dame / 19e Avenue",
        "10": "Notre-Dame / 16e Avenue",
        "11": "Notre-Dame / 14e Avenue",
        "12": "Notre-Dame / Saint-Jean-Baptiste",
        "13": "Saint-Jean-Baptiste / Victoria",
        "14": "Saint-Jean-Baptiste / de la Gauchetiere",
        "15": "Saint-Jean-Baptiste / Rene-Levesque",
        "16": "Place Pointe-aux-Trembles",
        "17": "Saint-Jean-Baptiste / de Montigny",
        "18": "Saint-Jean-Baptiste / Ontario",
        "19": "Saint-Jean-Baptiste / Sherbrooke",
        "20": "Saint-Jean-Baptiste / Industriel",
        "21": "Saint-Jean-Baptiste / Urgel-Charbonneau",
        "22": "Saint-Jean-Baptiste / Henri-Bourassa",
        "23": "Saint-Jean-Baptiste / No 10905",
        "24": "Saint-Jean-Baptiste / Armand-Chaput",
        "25": "Armand-Chaput / No 11410",
        "26": "Centre Riviere-des-Prairies",
        "27": "Armand-Chaput / Rolland-Jeanneau",
        "28": "89e Avenue / Maurice-Duplessis",
        "29": "Maurice-Duplessis / 87e Avenue",
        "30": "Gare Riviere-des-Prairies"
    }
}

=== Devitzer/SMPTProject/public/Lines/202.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 202,
    "lineName": "Ile-Bizard",
    "from": "Ile-Mercier",
    "to": "LOOP",
    "stops": {
        "1": "Ile-Mercier",
        "2": "Mercier / Louis-Roch",
        "3": "Louis-Roch / Cherrier",
        "4": "Cherrier / de l'Eglise",
        "5": "Cherrier / Dollard",
        "6": "Cherrier / des Pres",
        "7": "Cherrier / du Pont",
        "8": "Cherrier / Jacques Bizard",
        "9": "Cherrier / Saint-Pierre",
        "10": "Cherrier / de Blanzy",
        "11": "Cherrier / Soupras",
        "12": "Cherrier / Leo-Lorrain",
        "13": "Cherrier / Pierre-Foretier",
        "14": "Cherrier / Proulx",
        "15": "Cherrier / Triolet",
        "16": "Cherrier / Emile",
        "17": "Cherrier / Chaurset",
        "18": "Cherrier / Begin",
        "19": "Dutour / des Ormes",
        "20": "Dutour / des Vinaigriers",
        "21": "Dutour / des Aulnes",
        "22": "Dutour / Noyers",
        "23": "Dutour / des Erables",
        "24": "Dutour / Patenaude",
        "25": "Bord-du-Lac / Latraverse",
        "26": "Bord-du-Lac / Blouin",
        "27": "Bord-du-Lac / 2e Avenue",
        "28": "Bord-du-Lac / 4e Avenue",
        "29": "Bord-du-Lac / No 2317",
        "30": "Bord-du-Lac / No 2305",
        "31": "Bord-du-Lac / Boismeru",
        "32": "Bord-du-Lac / Bord-du-Lac",
        "33": "Bord-du-Lac / des Cageux",
        "34": "Bord-du-Lac / Phillippe-Delisle",
        "35": "Bord-du-Lac / Chateauneuf",
        "36": "Bord-du-Lac / Beaudet",
        "37": "Bord-du-Lac / de l'Eglise",
        "38": "de l'Eglise / du Golf",
        "39": "de l'Eglise / Alphonse-Desjardins",
        "40": "de l'Eglise / North Ridge",
        "41": "de l'Eglise / No 985",
        "42": "de l'Eglise / South Ridge",
        "43": "de l'Eglise / Robert N",
        "44": "de l'Eglise / Louise-Bizard",
        "45": "de l'Eglise / Robert S",
        "46": "de l'Eglise / Chevremont",
        "47": "Ecole Jacques-Bizard",
        "48": "de l'Eglise / Cherrier",
        "49": "Cherrier / Louis-Roch",
        "50": "Louis-Roch / Mercier",
        "51": "Ile-Mercier"
    }
}

=== Devitzer/SMPTProject/public/Lines/73.json
{
    "$schema": "./LineSchema.json",
    "frequent": false,
    "lineNumber": 73,
    "lineName": "Hochelaga",
    "from": "Station Frontenac",
    "to": "Station Honore-Beaugrand",
    "stops": {
        "1": "Station Frontenac",
        "2": "Frontenac / de Rouen",
        "3": "Frontenac / Hochelaga",
        "4": "Hochelaga / Hogan",
        "5": "Hochelaga / Florian",
        "6": "Station Prefontaine",
        "7": "Hochelaga / Dezery",
        "8": "Hochelaga / Davidson",
        "9": "Station Joliette",
        "10": "Hochelaga / Nicolet",
        "11": "Hochelaga / Bourbonniere",
        "12": "Hochelaga / Charlemagne",
        "13": "Hochelaga / Pie-IX",
        "14": "Hochelaga / de la Salle",
        "15": "Hochelaga / Bennett",
        "16": "Hochelaga / Sicard",
        "17": "Hochelaga / Theodore",
        "18": "Hochelaga / Viau",
        "19": "Hochelaga / Assomption",
        "20": "Hochelaga / Dickson",
        "21": "Hochelaga / Lacordaire",
        "22": "Hochelaga / Bossuet",
        "23": "Hochelaga / du Quesne",
        "24": "Polyvalent Edouard-Montpetit",
        "25": "Hochelaga / Langelier",
        "26": "Hochelaga / Desautels",
        "27": "Hochelaga / Haig",
        "28": "Hochelaga / Beauclerk",
        "29": "Centre Fernand-Seguin",
        "30": "Hochelaga / No 7401",
        "31": "Hochelaga / Lepailleur",
        "32": "Hochelaga / Honore-Beaugrand",
        "33": "Hochelaga / Liebert",
        "34": "Hochelaga / Lapointe",
        "35": "Hochelaga / Mercier",
        "36": "Hochelaga / Baldwin",
        "37": "Hochelaga / des Ormeaux",
        "38": "Hochelaga / Joffre",
        "39": "Hochelaga / Pierre-Bernand",
        "40": "Hochelaga / Taillon",
        "41": "Hochelaga / Aubry",
        "42": "Hochelaga / Fletcher",
        "43": "Hochelaga / de Contrecoeur",
        "44": "Hochelaga / Georges-V",
        "45": "Georges-V / Sainte-Claire",
        "46": "Georges-V / Sherbrooke",
        "47": "Sherbrooke / Hector",
        "48": "Sherbrooke / Bilaudeau",
        "49": "Sherbrooke / Jacques-Porlier",
        "50": "Sherbrooke / Paul-Pau",
        "51": "Sherbrooke / Desmarteau",
        "52": "Sherbrooke / Joffre",
        "53": "Sherbrooke / des Ormeaux",
        "54": "Sherbrooke / Balwdin",
        "55": "Sherbrooke / Mercier",
        "56": "Sherbrooke / Lapointe",
        "57": "Sherbrooke / Liebert",
        "58": "Station Honore-Beaugrand"
    }
}
